language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_database

node_js:  
  - "12.22.6"

before_script:
  - psql -c 'create database  my_database;' -U postgres
  - psql -U postgres -d my_database -a -f my_database.sql
services:
  - postgresql