language: node_js
node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_database
node_js:
  - "8.9.4"
before_script:
  - psql -c 'create database  my_database_tests;' -U postgres
  - psql -U postgres -d my_database_tests -a -f tables.sql
services:
  - postgresql